name: 'slugify'
description: 'slugify one input'
inputs:
  slugify_input:  # id of input
    description: 'what to slugify'
    required: true
    default: 'test/slug'
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/slugify.sh ${{ inputs.who-to-greet }}
      shell: bash
